apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: nginx:1.27.3-perl
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080
